import 'package:repathy/src/util/enum/pain_enum.dart';

const Map<PainEnum, String> painPathList = {
  PainEnum.abdominalPain: 'assets/pain/abdominal_pain.png',
  PainEnum.armPain: 'assets/pain/arm_pain.png',
  PainEnum.kneePain: 'assets/pain/knee_pain.png',
  PainEnum.elbowPain: 'assets/pain/elbow_pain.png',
  PainEnum.footPain: 'assets/pain/foot_pain.png',
  PainEnum.wristPain: 'assets/pain/wrist_pain.png',
  PainEnum.hipPain: 'assets/pain/hip_pain.png',
  PainEnum.anklePain: 'assets/pain/ankle_pain.png',
  PainEnum.legPain: 'assets/pain/leg_pain.png',
  PainEnum.handPain: 'assets/pain/hand_pain.png',
  PainEnum.shoulderPain: 'assets/pain/shoulder_pain.png',
  PainEnum.cervicalPain: 'assets/pain/cervical_pain.png',
  PainEnum.facialPain: 'assets/pain/facial_pain.png',
  PainEnum.lumbarPain: 'assets/pain/lumbar_pain.png',
  PainEnum.sacralPain: 'assets/pain/sacral_pain.png',
  PainEnum.anteriorSternalPain: 'assets/pain/anterior_sternal_pain.png',
  PainEnum.posteriorChestPain: 'assets/pain/posterior_chest_pain.png',
  PainEnum.upperTrapeziusPain: 'assets/pain/upper_trapezius_pain.png',
  PainEnum.migraine: 'assets/pain/migraine.png',
  PainEnum.headache: 'assets/pain/headache.png',
};

const Map<PainEnum, String> painPathSelectedList = {
  PainEnum.abdominalPain: 'assets/pain/abdominal_pain.psd',
  PainEnum.armPain: 'assets/pain/arm_pain.psd',
  PainEnum.kneePain: 'assets/pain/knee_pain.psd',
  PainEnum.elbowPain: 'assets/pain/elbow_pain.psd',
  PainEnum.footPain: 'assets/pain/foot_pain.psd',
  PainEnum.wristPain: 'assets/pain/wrist_pain.psd',
  PainEnum.hipPain: 'assets/pain/hip_pain.psd',
  PainEnum.anklePain: 'assets/pain/ankle_pain.psd',
  PainEnum.legPain: 'assets/pain/leg_pain.psd',
  PainEnum.handPain: 'assets/pain/hand_pain.psd',
  PainEnum.shoulderPain: 'assets/pain/shoulder_pain.psd',
  PainEnum.cervicalPain: 'assets/pain/cervical_pain.psd',
  PainEnum.facialPain: 'assets/pain/facial_pain.psd',
  PainEnum.lumbarPain: 'assets/pain/lumbar_pain.psd',
  PainEnum.sacralPain: 'assets/pain/sacral_pain.psd',
  PainEnum.anteriorSternalPain: 'assets/pain/anterior_sternal_pain.psd',
  PainEnum.posteriorChestPain: 'assets/pain/posterior_chest_pain.psd',
  PainEnum.upperTrapeziusPain: 'assets/pain/upper_trapezius_pain.psd',
  PainEnum.migraine: 'assets/pain/migraine.psd',
  PainEnum.headache: 'assets/pain/headache.psd',
};

const Map<PainEnum, String> painTitles = {
  PainEnum.abdominalPain: 'Dolore addominale',
  PainEnum.armPain: 'Dolore al braccio',
  PainEnum.kneePain: 'Dolore al ginocchio',
  PainEnum.elbowPain: 'Dolore al gomito',
  PainEnum.footPain: 'Dolore al piede',
  PainEnum.wristPain: 'Dolore al polso',
  PainEnum.hipPain: 'Dolore all\'anca',
  PainEnum.anklePain: 'Dolore alla caviglia',
  PainEnum.legPain: 'Doolore alla gamba',
  PainEnum.handPain: 'Dolore alla mano',
  PainEnum.shoulderPain: 'Dolore alla spalla',
  PainEnum.cervicalPain: 'Dolore cervicale',
  PainEnum.facialPain: 'Dolore facciali',
  PainEnum.lumbarPain: 'Dolore lombare',
  PainEnum.sacralPain: 'Dolore sacrale',
  PainEnum.anteriorSternalPain: 'Dolore sternale anteriore',
  PainEnum.posteriorChestPain: 'Dolore toracico posteriore',
  PainEnum.upperTrapeziusPain: 'Dolore trapezio superiore',
  PainEnum.migraine: 'Emicrania',
  PainEnum.headache: 'Mal di testa',
};
